platform :ios, '12.0'

target 'Todoey' do
  
  use_frameworks!
  
  # Pods for Todoey

  pod 'RealmSwift', '~>10'
  pod 'SwipeCellKit'
  
  pod 'ChameleonFramework/Swift', :git => 'https://github.com/wowansm/Chameleon.git', :branch => 'swift5'

end
